openapi: 3.0.0
info:
  title: TangoAPI
  version: '1.0'
  description: |-
    Tango API specification based on Tango 4.00.5.
    The API describes how to obtain authentication ticket and use it in the subsequent calls. The project list and preview request can be used through this API.
  contact:
    name: Shahid Shafiq
    email: shahid_shafiq@elixir.com
  license:
    name: Tango API License
servers:
  - url: 'http://localhost:3000/tango/api'
paths:
  /tickets:
    parameters: []
    post:
      summary: Get authentication ticket
      operationId: post-tickets
      responses:
        '201':
          description: Created
          content:
            application/xml-dtd:
              schema:
                type: object
                properties:
                  ticket:
                    type: string
                    format: byte
                required:
                  - ticket
        '401':
          description: Unauthorized
          content:
            text/html:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
          headers: {}
      tags:
        - Authentication
      description: Before accessign any resources from Tango API an authentication ticket is required. The ticket is issued only to authorized users.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Authorized username
                password:
                  type: string
                  description: Password for the username
              required:
                - username
                - password
            examples: {}
        description: The user information is provided in the body.
      parameters: []
  /tickets/site/id:
    get:
      summary: Obtain SiteID of the site
      tags: []
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: get-tickets-site-id
      description: Some API require numeric siteid. This API returns that numeric ID against a given site name.
      parameters:
        - schema:
            type: string
          in: query
          name: tango-ticket
          required: true
        - schema:
            type: string
          in: query
          name: siteName
          required: true
  /projects:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        appName:
                          type: string
                        clientApp:
                          type: string
                        companyId:
                          type: string
                        createDate:
                          type: string
                        description:
                          type: string
                        groupId:
                          type: string
                        id:
                          type: string
                        modifiedDate:
                          type: string
                        name:
                          type: string
                        path:
                          type: string
                        repoPath:
                          type: string
                        userName:
                          type: string
        '401':
          description: Unauthorized
      operationId: get-projects
      parameters:
        - schema:
            type: string
          in: query
          name: tango-ticket
        - schema:
            type: string
          in: query
          name: client-app
        - schema:
            type: string
          in: query
          name: site-id
        - schema:
            type: string
          in: query
          name: tenant-id
components:
  schemas: {}
  securitySchemes: {}
